### ISSUE TITLE
rpnphy/src/surface/urban_solar_abs.F90 : missing indices

### ISSUE THREAD

**Issue by frank2243** [armnlib/rpnphy#1]
In this following part of the code, indices JI needs to be added in the else statement :
```
!*      2.     SOLAR RADIATIONS FOR ROADS AND WALLS
!              ------------------------------------
!
DO JI=1,SIZE(PZENITH(:))
    IF (ABS(0.5*XPI-PZENITH(JI)) <  1.E-6) THEN
        IF(0.5*XPI-PZENITH(JI) >= 0.) ZTANZEN(JI)=TAN(0.5*XPI-1.E-6)
        IF(0.5*XPI-PZENITH(JI) < 0.) ZTANZEN(JI)=TAN(0.5*XPI+1.E-6)
    ELSE
        ZTANZEN(:) = TAN(PZENITH(:))
    ENDIF
ENDDO
```
`ZTANZEN(:) = TAN(PZENITH(:))` should become `ZTANZEN(JI) = TAN(PZENITH(JI))`

**Comment by frank2243** [comment]
There is another problem related to this part of the code.

If ZTANZEN is close to zero, this will cause a division by zero in section 2.1 (calculation of ZTHETA0) and cause the model to stop. This happens when PZENITH is very close to zero which means ZTANZEN would be equal to zero.

Here are two possible to solutions that could fix this : 
1. Adding an elseif statement after the first if in 2.0
```
DO JI=1,SIZE(PZENITH(:))
    IF (ABS(0.5*XPI-PZENITH(JI)) <  1.E-6) THEN
        IF(0.5*XPI-PZENITH(JI) >= 0.) ZTANZEN(JI)=TAN(0.5*XPI-1.E-6)
        IF(0.5*XPI-PZENITH(JI) < 0.) ZTANZEN(JI)=TAN(0.5*XPI+1.E-6)
    ELSEIF (ABS(PZENITH(JI)) <  1.E-6) THEN
        ZTANZEN(JI)=SIGN(1.,PZENITH(JI))*TAN(1.E-6)
    ELSE
        ZTANZEN(JI) = TAN(PZENITH(JI))
    ENDIF
ENDDO
```

2. Changing 2.1 by adding a where-elsewhere statement 
```
 WHERE (ABS(ZTANZEN(:)).le.0.001)
  ZTHETA0(:) = 0.5*XPI
ELSEWHERE
  ZTHETA0(:) = ASIN( MIN(ABS( 1./ZTANZEN(:))/PCAN_HW_RATIO(:), 1. ) )
ENDWHERE
```

**Comment by jeixav** [comment]
Applying https://github.com/armnlib/p3_teb/commit/b006952a4151521411b8dee13579233232c35da8 onto the HEAD of rpnphy should correct this issue.

Thank you for reporting the problem and suggesting revisions.

**Comment by jeixav** [comment]
Commit https://github.com/armnlib/rpnphy/commit/8c5158d7beaabea23910416b22bcbeeca6c28999 adds this correction to the current repository.
